Repository memochat/memochat-client, pull requests merged in 2022-08, with the labels that each got.

#8 ✨ feat: button 컴포넌트 개선
  .eslintignore
  src/components-deprecated/reusable/Button/Button.stories.tsx
  src/components/reusable/Button/Button.stories.tsx
  src/components/reusable/Button/Button.style.ts
  src/components/reusable/Button/Button.tsx
  src/components/reusable/Button/Button.type.ts
  src/components/reusable/Button/index.tsx
Labels: enhancement

#10 ✨ feat: steeper component 작성
  .lintstagedrc
  package.json
  src/components/reusable/Stepper/Stepper.stories.tsx
  src/components/reusable/Stepper/Stepper.style.ts
  src/components/reusable/Stepper/Stepper.tsx
  src/components/reusable/Stepper/Stepper.types.ts
  src/components/reusable/Stepper/index.ts
  yarn.lock
Labels: feature✨

#13 ✨ feat: 컴포넌트 생성 스크립트 추가
  .eslintignore
  package.json
  src/scripts/create-component.ts
  tsconfig.json
  yarn.lock
Labels: development💻

#14 ✨ feat: home/HomeHeader 컴포넌트 추가
  src/assets/icons/logo.svg
  src/components-deprecated/home/HomeHeader/HomeHeader.stories.tsx
  src/components-deprecated/home/HomeHeader/index.tsx
  src/components-deprecated/home/index.ts
  src/components-deprecated/reusable/ChatInput/TodoListInput/TodoItemInput/index.tsx
  src/components-deprecated/reusable/index.ts
  src/components/home/HomeHeader/HomeHeader.stories.tsx
  src/components/home/HomeHeader/HomeHeader.styles.ts
  src/components/home/HomeHeader/HomeHeader.tsx
  src/components/home/HomeHeader/index.ts
  src/components/reusable/Icon/Icon.stories.tsx
  src/components/reusable/Icon/Icon.tsx
  src/components/reusable/Icon/Icon.types.ts
  src/components/reusable/Icon/index.ts
Labels: feature✨

#16 feat: 룸 만들기, 룸 수정하기 모달 추가
  src/components-deprecated/reusable/Modal/Modal.stories.tsx
  src/components/reusable/Modal/Modal.stories.tsx
  src/components/reusable/Modal/Modal.styles.ts
  src/components/reusable/Modal/Modal.tsx
  src/components/reusable/Modal/Modal.types.ts
  src/components/reusable/Modal/ModalButtonGroup.ts
  src/components/reusable/Modal/ModalContents.ts
  src/components/reusable/Modal/index.ts
  src/components/reusable/ModalLayout/ModalLayout.stories.tsx
  src/components/reusable/ModalLayout/ModalLayout.styles.ts
  src/components/reusable/ModalLayout/ModalLayout.tsx
  src/components/reusable/ModalLayout/ModalLayout.types.ts
  src/components/reusable/ModalLayout/index.ts
  src/components/reusable/room/RoomTypeRadioGroup/RoomTypeRadioGroup.styles.ts
  src/components/reusable/room/RoomTypeRadioGroup/RoomTypeRadioGroup.tsx
  src/components/reusable/room/RoomTypeRadioGroup/RoomTypeRadioGroup.types.ts
  src/components/reusable/room/RoomTypeRadioGroup/index.ts
  src/components/reusable/room/UpsertRoomDialog/UpsertRoomDialog.stories.tsx
  src/components/reusable/room/UpsertRoomDialog/UpsertRoomDialog.styles.ts
  src/components/reusable/room/UpsertRoomDialog/UpsertRoomDialog.tsx
  src/components/reusable/room/UpsertRoomDialog/UpsertRoomDialog.types.ts
  src/components/reusable/room/UpsertRoomDialog/index.ts
  src/themes/color/theme.ts
  src/themes/color/types.ts
Labels: feature✨

#17 ✨ feat: 룸 설정페이지
  .eslintrc
  src/.DS_Store
  src/assets/.DS_Store
  src/assets/icons/.DS_Store
  src/assets/icons/arrow-left.svg
  src/assets/icons/arrow-right.svg
  src/assets/icons/index.ts
  src/components-deprecated/reusable/Modal/Modal.stories.tsx
  src/components/reusable/Icon/Icon.tsx
  src/components/reusable/Stepper/Stepper.stories.tsx
  src/components/roomDetail/RoomDetail/RoomDetail.stories.tsx
  src/components/roomDetail/RoomDetail/RoomDetail.styles.ts
  src/components/roomDetail/RoomDetail/RoomDetail.tsx
  src/components/roomDetail/RoomDetail/RoomDetail.types.ts
  src/components/roomDetail/RoomDetail/index.ts
  src/components/roomDetail/RoomDetailMenu/RomDetailMenu.stories.tsx
  src/components/roomDetail/RoomDetailMenu/RomDetailMenu.tsx
  src/components/roomDetail/RoomDetailMenu/RoomDetailMenu.styles.ts
  src/components/roomDetail/RoomDetailMenu/RoomDetailMenu.types.ts
  src/components/roomDetail/RoomDetailMenu/index.ts
  src/pages/rooms/[id]/detail.tsx
  src/themes/color/Color.stories.tsx
  src/themes/typography/Typography.stories.tsx
Labels: feature✨

#18 ✨ feat Room 메모 작성폼
  .gitignore
  package.json
  public/images/big-chat.png
  src/.DS_Store
  src/assets/.DS_Store
  src/assets/icons/.DS_Store
  src/assets/icons/album.svg
  src/assets/icons/camera.svg
  src/assets/icons/index.ts
  src/assets/icons/pencil.svg
  src/assets/icons/send.svg
  src/components/reusable/Icon/Icon.tsx
  src/components/room/RoomMemoForm/RoomMemoForm.stories.tsx
  src/components/room/RoomMemoForm/RoomMemoForm.styles.ts
  src/components/room/RoomMemoForm/RoomMemoForm.tsx
  src/components/room/RoomMemoForm/RoomMemoForm.types.ts
  src/components/room/RoomMemoForm/index.ts
  src/hooks/useMemoForm.tsx
  yarn.lock
Labels: feature✨
