Repository memochat/memochat-client, pull requests merged in 2022-10, with the labels that each got.

#39 refactor: ♻️ Header 리팩토링
  src/pages/rooms/[id]/images-and-videos/images-and-videos.styles.ts
  src/pages/rooms/[id]/images-and-videos/index.page.tsx
  src/shared/components/BackButton/BackButton.styles.ts
  src/shared/components/BackButton/BackButton.tsx
  src/shared/components/BackButton/BackButton.types.ts
  src/shared/components/BackButton/index.ts
  src/shared/components/Header/Header.stories.tsx
  src/shared/components/Header/Header.styles.ts
  src/shared/components/Header/Header.tsx
  src/shared/components/Header/Header.types.ts
Labels: refactor

#40 feat: :sparkles: react-toastify 적용 및 커스텀
  .storybook/preview.js
  package.json
  src/pages/_app.page.tsx
  src/shared/components/ToastContainer/ToastContainer.stories.tsx
  src/shared/components/ToastContainer/ToastContainer.tsx
  src/shared/components/ToastContainer/index.ts
  src/shared/utils/toast.tsx
  src/themes/GlobalStyle.tsx
  yarn.lock
Labels: feature✨

#37 feat: :sparkles: 인증처리 atom추가
  .storybook/preview.js
  package.json
  src/features/auth/hooks/useAuth.tsx
  src/modules/recoil/auth.ts
  src/pages/_app.page.tsx
  src/pages/home/index.page.tsx
  yarn.lock
Labels: feature✨

#42 다국어 지원 i18n모듈 설정
  package.json
  src/modules/i18n/index.ts
  src/pages/_app.page.tsx
  src/shared/constant/i18nResource.ts
  yarn.lock
Labels: development💻

#43 feat: :sparkles: add react-query hydration
  .vscode/settings.json
  package.json
  src/features/auth/hooks/useAuth.tsx
  src/features/user/api/useUsersMeQuery.ts
  src/pages/_app.page.tsx
  src/pages/home/index.page.tsx
  src/pages/rooms/[id]/images-and-videos/index.page.tsx
  src/pages/rooms/[id]/links/index.page.tsx
  src/pages/rooms/[id]/setting/index.page.tsx
  src/pages/signin/index.page.tsx
  src/shared/types/next.d.ts
  yarn.lock
Labels: feature✨

#44 feat: :sparkles: 페이지간 이동시 보이는 로딩 컴포넌트 작성
  package.json
  src/assets/lotti/loading.json
  src/pages/_app.page.tsx
  src/pages/signin/index.page.tsx
  src/shared/components/Loading/Loading.stories.tsx
  src/shared/components/Loading/Loading.styles.ts
  src/shared/components/Loading/Loading.tsx
  src/shared/components/Loading/Loading.types.ts
  src/shared/components/Loading/index.ts
  src/shared/styles/GlobalStyle.tsx
  src/shared/styles/themes/zIndex/theme.ts
  src/shared/styles/themes/zIndex/types.ts
  yarn.lock
Labels: feature✨
