Repository memochat/memochat-client, pull requests merged in 2022-09, with the labels that each got.

#21 feat: 룸 컴포넌트, 룸리스트 컴포넌트 마크업 추가
  package.json
  public/images/basket.png
  public/images/calendar.png
  public/images/cash.png
  public/images/chat.png
  public/images/notepad.png
  src/components-deprecated/home/RoomList/RoomCard/index.tsx
  src/components-deprecated/home/RoomList/RoomList.stories.tsx
  src/components-deprecated/home/RoomList/index.tsx
  src/components-deprecated/home/RoomList/mock.ts
  src/components-deprecated/home/index.ts
  src/features/room/components/RoomList/RoomList.stories.tsx
  src/features/room/components/RoomList/RoomList.tsx
  src/features/room/components/RoomList/index.ts
  src/features/room/components/RoomListItem/RoomListItem.stories.tsx
  src/features/room/components/RoomListItem/RoomListItem.styles.ts
  src/features/room/components/RoomListItem/RoomListItem.tsx
  src/features/room/components/RoomListItem/RoomListItem.types.ts
  src/features/room/components/RoomListItem/index.ts
  src/features/room/components/UpsertRoomDialog/UpsertRoomDialog.tsx
  src/features/room/helpers/room.ts
  src/shared/styles/index.ts
  yarn.lock
Labels: feature✨

#23 feat: :sparkles: shared Checkbox 컴포넌트 추가
  src/assets/icons/check.svg
  src/assets/icons/index.ts
  src/shared/components/Checkbox/Checkbox.stories.tsx
  src/shared/components/Checkbox/Checkbox.styles.ts
  src/shared/components/Checkbox/Checkbox.tsx
  src/shared/components/Checkbox/Checkbox.types.ts
  src/shared/components/Checkbox/index.ts
Labels: feature✨

#25 feat: :sparkles: feat: zindex 테마 추가
  src/pages/rooms/[id]/detail.styles.ts
  src/shared/components/ModalLayout/ModalLayout.styles.ts
  src/themes/index.ts
  src/themes/theme.ts
  src/themes/zIndex/index.ts
  src/themes/zIndex/theme.ts
  src/themes/zIndex/types.ts
Labels: feature✨

#26 feat: :sparkles: 헤더컴포넌트 추가
  src/features/home/components/HomeHeader/HomeHeader.stories.tsx
  src/features/home/components/HomeHeader/HomeHeader.styles.ts
  src/features/home/components/HomeHeader/HomeHeader.tsx
  src/features/home/components/HomeHeader/HomeHeader.types.ts
  src/features/home/components/HomeHeader/index.ts
  src/features/home/components/index.ts
  src/pages/home/HomeHeader.tsx
  src/shared/components/Header/Header.stories.tsx
  src/shared/components/Header/Header.styles.ts
  src/shared/components/Header/Header.tsx
  src/shared/components/Header/Header.types.ts
  src/shared/components/Header/index.ts
  src/shared/components/index.ts
Labels: feature✨

#30 fix: 🐛 스토리북에서 이미지 안나오는 이슈 수정
  .storybook/main.js
  .storybook/preview.js
  package.json
  src/shared/components/Stepper/Stepper.style.ts
  src/types/next-env.d.ts
  yarn.lock
Labels: bug🐛

#28 feat: ✨ shared/MainLayout 추가
  .storybook/preview.js
  src/pages/_app.page.tsx
  src/pages/home/home.styles.ts
  src/pages/rooms/[id]/detail.styles.ts
  src/pages/rooms/[id]/index.page.tsx
  src/pages/signin/signin.styles.ts
  src/pages/signup/signup.styles.ts
  src/shared/components/MainLayout/MainLayout.styles.ts
  src/shared/components/MainLayout/MainLayout.tsx
  src/shared/components/MainLayout/MainLayout.types.ts
  src/shared/components/MainLayout/index.ts
  src/themes/breakpoints/index.ts
  src/themes/breakpoints/theme.ts
  src/themes/breakpoints/types.ts
  src/themes/theme.ts
  styles/global.css
Labels: feature✨

#31 chore: :construction_worker: conventional commit 불필요한 promt안나오도록 변경, ci체크하는 prompt나오도록 변경
  .vscode/settings.json
Labels: development💻

#22 ✨ feat: 바텀시트 Ui
  .storybook/preview.js
  src/pages/_document.page.tsx
  src/shared/components/BottomSheet/BottomSheet.stories.tsx
  src/shared/components/BottomSheet/BottomSheet.styles.ts
  src/shared/components/BottomSheet/BottomSheet.tsx
  src/shared/components/BottomSheet/BottomSheet.types.ts
  src/shared/components/BottomSheet/index.ts
Labels: feature✨

#35 feat: :sparkles: LinkManageListItem 추가
  src/features/chat/components/LinkManageListItem/LinkManageListItem.stories.tsx
  src/features/chat/components/LinkManageListItem/LinkManageListItem.styles.ts
  src/features/chat/components/LinkManageListItem/LinkManageListItem.tsx
  src/features/chat/components/LinkManageListItem/LinkManageListItem.types.ts
  src/features/chat/components/LinkManageListItem/index.ts
  src/shared/components/Checkbox/Checkbox.types.ts
Labels: feature✨

#34 feat: :sparkles: ImageManageListItem 컴포넌트 추가
  src/features/chat/components/ImageManageListItem/ImageManageListItem.stories.tsx
  src/features/chat/components/ImageManageListItem/ImageManageListItem.styles.ts
  src/features/chat/components/ImageManageListItem/ImageManageListItem.tsx
  src/features/chat/components/ImageManageListItem/ImageManageListItem.types.ts
  src/features/chat/components/ImageManageListItem/index.ts
  src/shared/components/Checkbox/Checkbox.types.ts
Labels: feature✨

#36 feat: :sparkles: 사진, 동영상 모아보기 마크업 추가
  src/assets/icons/check.svg
  src/assets/icons/close.svg
  src/assets/icons/download.svg
  src/assets/icons/index.ts
  src/features/chat/components/ImageManageListItem/ImageManageListItem.styles.ts
  src/features/chat/components/ImageManageListItem/ImageManageListItem.tsx
  src/features/chat/components/ImageManageListItem/ImageManageListItem.types.ts
  src/pages/rooms/[id]/images-and-videos/images-and-videos.stories.tsx
  src/pages/rooms/[id]/images-and-videos/images-and-videos.styles.ts
  src/pages/rooms/[id]/images-and-videos/images-and-videos.types.ts
  src/pages/rooms/[id]/images-and-videos/index.page.tsx
  src/shared/components/ConfirmModal/ConfirmModal.styles.ts
  src/shared/components/Header/Header.styles.ts
  src/shared/components/Header/Header.tsx
  src/shared/hooks/useConfirm.ts
Labels: feature✨

#33 feat: :sparkles: settings 페이지 작성
  public/images/settings.png
  src/assets/icons/avatar.svg
  src/assets/icons/chat.svg
  src/assets/icons/index.ts
  src/assets/icons/lang.svg
  src/features/settings/components/SettingDetailMenu/SettingDetailMenu.stories.tsx
  src/features/settings/components/SettingDetailMenu/SettingDetailMenu.styles.ts
  src/features/settings/components/SettingDetailMenu/SettingDetailMenu.tsx
  src/features/settings/components/SettingDetailMenu/SettingDetailMenu.types.ts
  src/features/settings/components/SettingDetailMenu/index.ts
  src/features/settings/hooks/useChangePasswordForm.tsx
  src/pages/_app.page.tsx
  src/pages/settings/account/account.stories.tsx
  src/pages/settings/account/account.styles.ts
  src/pages/settings/account/change-password/changepassword.styles.ts
  src/pages/settings/account/change-password/index.page.tsx
  src/pages/settings/account/index.page.tsx
  src/pages/settings/index.page.tsx
  src/pages/settings/settings.stories.tsx
  src/pages/settings/settings.styles.ts
  src/shared/components/index.ts
  src/styles/global.css
  tsconfig.json
  tsconfig.paths.json
Labels: feature✨
